### PR TITLE
Update plugin-publish plugin

### PR DESCRIPTION
**Pull request by timyates**
Hiya, I was doing a scan of the Gradle Plugin Portal and noticed you are using an old version of the `plugin-publish-plugin`.

There was a [bug in versions prior to 0.9.7](https://discuss.gradle.org/t/plugin-authors-please-use-the-latest-plugin-publish-plugin-others-may-result-in-a-broken-upload/23573), where artifacts would silently not be pushed into the repo, which means the latest version of your plugin will not work properly when people apply it to their build.

Upgrading to the latest version of the `plugin-publish-plugin` will fix this, but this will require pushing a new version of your plugin.

1. apply the PR
2. publish a new version of your plugin
3. let us know if you want us to remove the broken version `0.12`

Thanks (and sorry about that).

Let us know here [or in the forums](https://discuss.gradle.org/c/help-discuss/plugin-portal) if you need more assistance.

### CODE REVIEW

**Comment by JayStGelais** [comment]
@timyates Thank you for finding this and the PR that fixes it. 

I'm not too familiar with how the plugin repository works, but will I be able to republish without you removing the broken version first?If not, please go ahead and remove it and I will republish the version.

**Comment by timyates** [comment]
It won't let you republish an identical version, I'd have to remove it first...  One sec, I'll get it done, and let you know when you're good to go 👍

**Comment by timyates** [comment]
Cool, that's 0.12 removed, can you try re-publishing?

**Comment by JayStGelais** [comment]
@timyates Thank you. I have republished 0.12 using the updated plugin.

**Comment by timyates** [comment]
Cool!  Checked it, and it resolves perfectly now 😄 

Thanks!  And have fun!

**Pull request merged**
