### PR TITLE
Allowing multiple tags with ignored ones

### PR DESCRIPTION
**Pull request by fernandotnl**
# WHAT
Now it's only possible to use multiple tags if none of them is a ignored one (e.g. ~@ignore)

# WHY
Issue #32 has a request to be able to use multiple tags with ignored ones

### CODE REVIEW

**Comment by JayStGelais** [comment]
@fernandotnl Your pull request is failing the Codenarc checks. Run `./gradlew check` locally and view the report.

**Comment by fernandotnl** [comment]
Just fixed the Codenarc issues.

**Comment by fernandotnl** [comment]
Hello @JayStGelais. How soon you think you can create a version with this fix?

**Comment by JayStGelais** [comment]
@fernandotnl I have an open question in the code review you haven't addressed.

**Comment by fernandotnl** [comment]
I can't see this open question. I fixed the Conecarc issues and all checks have passed.

**Comment by JayStGelais** [comment]
Version 0.10 has been published with this change.

@fernandotnl

**Comment by fernandotnl** [comment]
Thank you!

**Pull request merged**
