### PR TITLE
Multiple tags with ignored ones

### PR DESCRIPTION
**Pull request by fernandotnl**
We need to divide the insertion of "--tags" and the actual tags in the args list to make it work.

### CODE REVIEW

**Comment by JayStGelais** [comment]
@fernandotnl 

I had assumed the command had been constructed properly with the last pull request. Shame on me for not verifying behaviour locally before accepting the previous request, I have been out of using cucumber on a regular basis and didn't have a test suite build handy to try this out.

Before we publish another version, what testing have you done to verify that cucumber runs correctly with these inputs? 

You can publish this plugin to maven local then wire up your test suite's build to pull that version of the plugin.

**Comment by fernandotnl** [comment]
I just added a feature test that I used to make sure that this feature is working fine.
I'm sorry about the first PR, I read the library doc and I thought that a single string would work for us but we actually needed to split the '--args' and it's value into two differents elements in args list.
Also, I was editing the files via github instead of using my local cloned repository and because of that I missed some issues. This time I tested it properly and it's working exactly the way I was planning at the beginning.

**Comment by fernandotnl** [comment]
@JayStGelais Do you need anything else or are these tests okay?

**Comment by JayStGelais** [comment]
This has been released as version 0.11.

**Comment by fernandotnl** [comment]
Thank you!

**Pull request merged**
