### PR TITLE
Optimize CucumberRunner by passing feature file batches

### PR DESCRIPTION
**Pull request by ljank**
otherwise tag filtering wastes lots of time when there are lots of feature files and just a few of them match lookup tag.

Motivation: At Vinted we have 216 cucumber spec files and our average spec takes about 1 minute to run. While working on isolated features we're running just a few (most of the time — just one) cucumber spec(s) on our local machines for faster feedback loop. Without this optimisation finding feature file with special tag wastes 7+ minutes. With the optimisation there's no more process spawning overhead for each spec file and specially tagged specs start running immediately!

@JayStGelais

### CODE REVIEW

**Comment by JayStGelais** [comment]
@ljank 

I've stepped away form maintaining this plugin. We have 2 new maintainers though, that will take a look at this. @vigneshrr90 and @shweta2202

**Comment by andrcuns** [comment]
This however really complicated understanding which log file contains which executions. While it might be helpful in Your case, it's opposite for ours for example.

**Comment by andrcuns** [comment]
We have extensive logging within our tests which would not be visible in native reports, only the upper layer of cucumber steps and stack trace, which might not always be enough.
So if I run a pack of tests and some of them fail, I wan't to be able to check the console output be it locally or in form of saved txt files on jenkins for example.
Simply because output is redirected to a file and thatš the only place it is available, it is not a good idea in general to create a solution where one can't understand what those files actually contain.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.

**Pull request closed without merging**
